apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: nextcloud
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1001
          containers:
          - name: backup
            image: postgres:15
            securityContext:
              runAsUser: 1001
            env:
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: nextcloud-secrets
                    key: POSTGRES_PASSWORD
              - name: PGUSER
                valueFrom:
                  secretKeyRef:
                    name: nextcloud-secrets
                    key: POSTGRES_USER
              - name: PGDATABASE
                valueFrom:
                  secretKeyRef:
                    name: nextcloud-secrets
                    key: POSTGRES_DB
            command:
              - /bin/bash
              - -c
              - |
                echo "start"
                mkdir -p /backup
                pg_dump -h postgresql -U $PGUSER $PGDATABASE > /backup/backup_$(date +%F).sql
                echo "file: /backup/backup_$(date +%F).sql"
                find /backup/ -type f -mtime +7 -exec rm -f {} \;
                echo "fin"
            volumeMounts:
              - name: backup-volume
                mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: backup-pvc
