{{- if .Values.nextcloud.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-nextcloud
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nextcloud
    {{- include "commonLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud  # Селектор без цвета
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nextcloud  # Метки без цвета
        {{- include "commonLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 33:33 /mnt/data /var/www/html && chmod 0770 /mnt/data /var/www/html"]
          volumeMounts:
            - mountPath: /mnt/data
              name: nextcloud-storage-nfs
            - mountPath: /var/www/html
              name: nextcloud-storage
      containers:
        - image: {{ .Values.nextcloud.image }}
          name: nextcloud
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: {{ .Values.global.secretName }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: {{ .Values.global.secretName }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: {{ .Values.global.secretName }}
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: NEXTCLOUD_ADMIN_USER
                  name: {{ .Values.global.secretName }}
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: NEXTCLOUD_ADMIN_PASSWORD
                  name: {{ .Values.global.secretName }}
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: {{ .Values.global.domain }}
            - name: NEXTCLOUD_DATA_DIR
              value: /mnt/data
            - name: APACHE_DISABLE_REWRITE_IP
              value: "1"
            - name: OVERWRITEHOST
              value: {{ .Values.global.domain }}
            - name: OVERWRITEPROTOCOL
              value: https
            - name: OVERWRITECLIURL
              value: https://{{ .Values.global.domain }}
            - name: OVERWRITEWEBROOT
              value: "/"
            - name: PHP_MEMORY_LIMIT
              value: 4G
            - name: PHP_UPLOAD_LIMIT
              value: 1G
            - name: TZ
              value: {{ .Values.global.timezone }}
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-storage
            - mountPath: /mnt/data
              name: nextcloud-storage-nfs
      volumes:
        - name: nextcloud-storage
          persistentVolumeClaim:
            claimName: {{ include "fullname" . }}-nextcloud-pvc
        - name: nextcloud-storage-nfs
          persistentVolumeClaim:
            claimName: {{ include "fullname" . }}-nextcloud-pvc-nfs
{{- end }}