prometheus:
  enabled: true
  isDefault: false
  url: http://{{ include "prometheus.fullname" . }}:{{ .Values.prometheus.server.service.servicePort }}
  datasource:
    jsonData: "{}"
  persistence:
    enabled: true
    storageClassName: local-path
    size: 5Gi

loki:
  enabled: true
  isDefault: true
  url: http://{{ include "loki.serviceName" . }}:{{ .Values.loki.service.port }}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  datasource:
    jsonData: "{}"
    uid: "loki"
  persistence:
    enabled: true
    storageClassName: local-path 
    size: 5Gi

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}-loki.{{ .Release.Namespace }}.svc.cluster.local:3100/loki/api/v1/push

grafana:
  enabled: true
  sidecar:
    datasources:
      label: ""
      labelValue: ""
      enabled: true
      maxLines: 1000
  image:
    tag: 10.0.2
  persistence:
    enabled: true
    storageClassName: local-path
    size: 2Gi
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
    labels: {}
    path: /
    pathType: Prefix
    hosts:
      - grafana.monitoring.local.cloud
