{{- if .Values.nextcloud.enabled }}
{{- $color := include "deployment.color" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-nextcloud-{{ $color }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nextcloud
    deployment-color: {{ $color }}
    {{- include "commonLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
      deployment-color: {{ $color }}
  strategy:
    {{- if eq .Values.deployment.strategy "rolling" }}
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    {{- else }}
    type: Recreate
    {{- end }}
  template:
    metadata:
      labels:
        app: nextcloud
        deployment-color: {{ $color }}
        {{- include "commonLabels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.nextcloud.image }}
          name: nextcloud
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: redis
            - name: POSTGRES_HOST
              value: postgresql
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: {{ .Values.global.secretName }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: {{ .Values.global.secretName }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: {{ .Values.global.secretName }}
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: NEXTCLOUD_ADMIN_USER
                  name: {{ .Values.global.secretName }}
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: NEXTCLOUD_ADMIN_PASSWORD
                  name: {{ .Values.global.secretName }}
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: {{ .Values.global.domain }}
            - name: NEXTCLOUD_DATA_DIR
              value: /mnt/data
            - name: APACHE_DISABLE_REWRITE_IP
              value: "1"
            - name: OVERWRITEHOST
              value: {{ .Values.global.domain }}
            - name: OVERWRITEPROTOCOL
              value: https
            - name: OVERWRITECLIURL
              value: https://{{ .Values.global.domain }}
            - name: OVERWRITEWEBROOT
              value: "/"
            - name: PHP_MEMORY_LIMIT
              value: 4G
            - name: PHP_UPLOAD_LIMIT
              value: 1G
            - name: TZ
              value: {{ .Values.global.timezone }}
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-storage
              readOnly: false
            - mountPath: /mnt/data
              name: nextcloud-storage-nfs
              readOnly: false
      volumes:
        - name: nextcloud-storage
          persistentVolumeClaim:
            claimName: {{ include "fullname" . }}-nextcloud-pvc
        - name: nextcloud-storage-nfs
          persistentVolumeClaim:
            claimName: {{ include "fullname" . }}-nextcloud-pvc-nfs
{{- end }}