{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: {{ .Values.redis.image }}
          name: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          env:
            - name: TZ
              value: {{ .Values.global.timezone }}
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: {{ include "fullname" . }}-redis-pvc
{{- end }}