apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nextcloud
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: nextcloud
  namespaceSelector:
    matchNames:
      - nextcloud
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
