apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter
        env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://nextclouduser:nextcloudpass@postgresql.nextcloud.svc.cluster.local:5432/nextclouddb?sslmode=disable"
        ports:
        - containerPort: 9187
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: nextcloud
  labels:
    app: postgres-exporter
spec:
  ports:
  - port: 9187
    targetPort: 9187
    name: metrics
  selector:
    app: postgres-exporter
