apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter
        args:
        - "--redis.addr=redis://redis.nextcloud.svc.cluster.local:6379"
        ports:
        - containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: nextcloud
  labels:
    app: redis-exporter
spec:
  ports:
  - port: 9121
    targetPort: 9121
    name: metrics
  selector:
    app: redis-exporter
