name: Deploy Nextcloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Helm Chart
        uses: azure/setup-helm@v3
        with:
          version: "3.12.0"
        run: helm lint ./helm

  deploy:
    needs: lint
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm and kubectl
        uses: azure/setup-helm@v3
        with:
          version: "3.12.0"
        run: |
          helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
          helm repo update

      - name: Configure Kubernetes Access
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy Nextcloud
        run: |
          helm upgrade --install nextcloud ./helm \
            --namespace nextcloud \
            --create-namespace \
            --set global.namespace=nextcloud \
            --set redis.enabled=true \
            --set postgresql.enabled=true \
            --set certManager.enabled=true \
            --set deployment.strategy=blue-green
